### ISSUE TITLE
Quality_Assessment.sh error

### ISSUE THREAD

**Issue by ChaochihL** [MorrellLAB/sequence_handling#16]
Error file message:

```
/bin/bash: fastqc: command not found
```

Fixed by adding `module load fastqc` line to `Quality_Assessment.sh`.

**Comment by mojaveazure** [comment]
On line 276 of the Config file, uncomment the line for loading the FastQC module.

That would be changing the line from this:

``` shell
#module load fastqc
```

to this:

``` shell
module load fastqc
```

**Comment by mojaveazure** [comment]
@liux1299 Did this work?

**Comment by ChaochihL** [comment]
Wasn't able to test it yet, my other samples were already running at that time.

I will test it on the 3 samples I have to re-run and let you know.

**Comment by ChaochihL** [comment]
Works
