### ISSUE TITLE
Error in naming of processed BAM samples

### ISSUE THREAD

**Issue by ChaochihL** [MorrellLAB/sequence_handling#18]
## Type of issue
- [x] Bug
- [ ] Feature request

---
### Have you looked at the wiki?

The wiki is located [here](https://github.com/MorrellLAB/sequence_handling/wiki)
- [ ] Yes
- [ ] No
### Which handler are you having trouble with?

Process_SAM
### What is the error message being generated?

``` shell
-bash-4.1$ ./sequence_handling 7 ~/Config_125bp 
sequence_handling: Mapping coverage...
/home/morrellp/liux1299/Shared/WBDC_inversions/SAM_Processing/Barley_Inversions_deduped_BAM.txt doesn't exist, exiting...
```
### Copy the part of the config file used by this handler

``` shell
28 #   Where is the list of processed BAM samples?
     29 #       This is used for Coverage_Map and Indel_Realignment
     30 #       If using SAM_Processing, then leave as is
     31 BAM_SAMPLES=${OUT_DIR}/SAM_Processing/${PROJECT}_deduped_BAM.txt
```

Currently the output name is called:

```
Barley_Inversions_Processed_BAM.txt
```

``` shell
#   Handler-specific values go here

```

``` shell
#   Dependency definitions go here

```
### Has anyone else been able to replicate your error?
- [ ] Yes
- [ ] No

---
### What new thing is being added?
- [ ] New handler
- [ ] Modification to handler
### Do you have a script for this change? Please note that we can implement your code faster if you write everything as [BASH functions](http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-8.html).
- [ ] Yes
- [ ] No

If yes, please make sure the code is posted online and link to it below:

[name of code exerpt](link.to.code.exerpt)

Good hosting sites are [GitHub](https://github.com) and [GitHub Gist](https://gist.github.com).

**Comment by mojaveazure** [comment]
Fixed.
