### ISSUE TITLE
clarifying Config setup

### ISSUE THREAD

**Issue by pmorrell** [MorrellLAB/sequence_handling#22]
## Type of issue
- [ ] Bug
- [ ] Feature request

---
### Have you looked at the wiki?

The wiki is located [here](https://github.com/MorrellLAB/sequence_handling/wiki)
- [X] Yes
- [ ] No
### Which handler are you having trouble with?

Config
### Describe your problem

On lines 34-36 of Config, it is not clear what delimiter should be used among columns? Should they be tab or space delimited?
### What is the error message being generated?

None

``` shell
# Put your error message here

```
### Copy the part of the config file used by this handler

``` shell
#   Shared values go here

```

``` shell
#   Handler-specific values go here

```

``` shell
#   Dependency definitions go here

```
### Has anyone else been able to replicate your error?
- [ ] Yes
- [X] No

---
### What new thing is being added?
- [ ] New handler
- [ X] Modification to handler
### Do you have a script for this change? Please note that we can implement your code faster if you write everything as [BASH functions](http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-8.html).
- [ ] Yes
- [ ] No

If yes, please make sure the code is posted online and link to it below:

[name of code exerpt](link.to.code.exerpt)

Good hosting sites are [GitHub](https://github.com) and [GitHub Gist](https://gist.github.com).

**Comment by mojaveazure** [comment]
Please see response for #23 regarding variables for `GBS_Demultiplex`

**Comment by Aerin13** [comment]
The lines in Config that you reference are related to GBS Demultiplexing, which is still incomplete. Since the Config file for this handler will almost definitely change before it is released, I'm closing this issue.
