### ISSUE TITLE
Config file changes needed

### ISSUE THREAD

**Issue by pmorrell** [MorrellLAB/sequence_handling#23]
In Config:
- I'm not sure what you are asking for between lines 36-40
  - This is "KEY_FILE="
- On lines 42-43, is this a BWA-specific setting? If so, this needs some clarification on how a value is chosen.
  - 
- On lines 45-46, was does partial overlap refer to? Does this mean overlap of paired end reads? Need to clarify. Of course, this is highly dependent on insert size and read length.
- On lines 48-49, "file type" has a couple of different meanings on a UNIX system. The "file" command gives you basic info, but generally there is plain text or binary. I think what you actually want here is file naming convention. Perhaps give an example.
- On lines 59-60, what are you asking for? Also, on line 3, what does "raw sample" mean? I assume it means original FASTQ files. Perhaps fix the language there.
- On line 255, identify the units for MAX_MEM

**Comment by mojaveazure** [comment]
`GBS_Demultiplex` is still in the still in the [works](https://github.com/MorrellLAB/sequence_handling#gbs_demultiplexer), so variables for this handler are still in limbo.

I have addressed the issues for variables outside of `GBS_Demultiplex`
