### ISSUE TITLE
Coverage Mapping Issue

### ISSUE THREAD

**Issue by ChaochihL** [MorrellLAB/sequence_handling#25]
## Type of issue
- [x] Bug
- [ ] Feature request

---
### Have you looked at the wiki?

The wiki is located [here](https://github.com/MorrellLAB/sequence_handling/wiki)
- [x] Yes
- [ ] No
### Which handler are you having trouble with?

Coverage Mapping
### Describe your problem

Coverage Mapping currently does not support BED files as input. It currently only plots for GFF files.
### What is the error message being generated?

``` shell
# Put your error message here

```
### Copy the part of the config file used by this handler

``` shell
#   Shared values go here

```

``` shell
#   Handler-specific values go here

```

``` shell
#   Dependency definitions go here

```
### Has anyone else been able to replicate your error?
- [ ] Yes
- [ ] No

---
### What new thing is being added?
- [ ] New handler
- [ ] Modification to handler
### Do you have a script for this change? Please note that we can implement your code faster if you write everything as [BASH functions](http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-8.html).
- [ ] Yes
- [x] No

If yes, please make sure the code is posted online and link to it below:

[name of code exerpt](link.to.code.exerpt)

Good hosting sites are [GitHub](https://github.com) and [GitHub Gist](https://gist.github.com).

**Comment by pmorrell** [comment]
I also go not output in '/CoveragePlots'. I found the following error message repeated in the output file:

```pmorrell@labqi046 [~/Apps/PHoffman/sequence_handling/ErrorFiles] % more MBE_Reference_Coverage_Mapping.e2863576
Collecting sample names...
Mapping coverage...
Finding coverage histograms...
Plotting coverage...
Creating R Library at /panfs/roc/groups/9/morrellp/pmorrell/Apps/PHoffman/sequence_handling/.RLibs 
Failed to install Hmisc 
Error in FUN(X[[i]], ...) : there is no package called 'Hmisc'
Calls: main -> batchInstall -> lapply -> FUN
Execution halted
```

**Comment by Aerin13** [comment]
As of commit [acc3405](https://github.com/MorrellLAB/sequence_handling/commit/acc3405505ee0d7e4d7c6c19d67dcc11b651e24d), Coverage_Mapping now accepts BED files as valid regions files. Coverage plotting is not currently supported, but is planned for a future version.
