### ISSUE TITLE
Paired end FASTQ have differed numbers of reads after adapter trimming

### ISSUE THREAD

**Issue by pmorrell** [MorrellLAB/sequence_handling#28]
## Type of issue

- [X ] Bug
- [ ] Feature request

---

### Have you looked at the wiki?

The wiki is located [here](https://github.com/MorrellLAB/sequence_handling/wiki)

- [X ] Yes
- [ ] No

### Which handler are you having trouble with?
Adapter_Trimming

### Describe your problem
Reads trimmed by scythe end up with paired ends out of sync. This is readily evident in that file sizes and file length differ for the two FASTQ files for each sample. This is not an issue with scythe, as running scythe on the command line will not produce an empty read.

### What is the error message being generated?
You can see the issue simply by looking at file sizes for reads in a pair. The problem is also evident in flagstat output after read mapping, as none of the reads map as "proper pairs." See the example below.

pmorrell@labqi046 [~/scratch/MBE_Barley/SAM_Processing/SAMtools/Finished] % bamtools stats -in H_spontaneum_OUH602_finished.bam

**********************************************
Stats for BAM file(s): 
**********************************************

Total reads:       49480787
Mapped reads:      48686120	(98.394%)
Forward strand:    24859439	(50.2406%)
Reverse strand:    24621348	(49.7594%)
Failed QC:         0	(0%)
Duplicates:        0	(0%)
Paired-end reads:  49480787	(100%)
'Proper-pairs':    0	(0%)
Both pairs mapped: 48153336	(97.3172%)
Read 1:            24739843
Read 2:            24740944
Singletons:        532784	(1.07675%)
```shell
# Put your error message here

```

### Copy the part of the config file used by this handler

```shell
#   Shared values go here

```

```shell
#   Handler-specific values go here

```

```shell
#   Dependency definitions go here

```

### Has anyone else been able to replicate your error?

- [X ] Yes
- [ ] No

---

### What new thing is being added?

- [ ] New handler
- [X ] Modification to handler

### Do you have a script for this change? Please note that we can implement your code faster if you write everything as [BASH functions](http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-8.html).

- [ ] Yes
- [X ] No

If yes, please make sure the code is posted online and link to it below:

I have not attempted to correct the handler, but I am writing a shell script which will check that FASTQ files have the same number of reads after adapter trimming.

[name of code exerpt](link.to.code.exerpt)

Good hosting sites are [GitHub](https://github.com) and [GitHub Gist](https://gist.github.com).

**Comment by mojaveazure** [comment]
Issue fixed with commit 963bd463137fef22212218d0802ebc53abd9591d
