### ISSUE TITLE
sequence_handling should use canonical paths

### ISSUE THREAD

**Issue by TomJKono** [MorrellLAB/sequence_handling#3]
Since qsub runs from the user's home directory, all of the relative paths in sequence_handling become broken by the scheduler. If invoked from the sequence_handling directory, $SEQUENCE_HANDLING becomes '.' which causes file not found errors. Should use 'pwd' to get canonical paths.

**Comment by mojaveazure** [comment]
Done for now. System-wide installation will be added in the future, which will change this.
