### ISSUE TITLE
Truncated Files with Picard Handler

### ISSUE THREAD

**Issue by TomJKono** [MorrellLAB/sequence_handling#30]
This is a complicated issue. I think I have a hunch about where it originates, though.

In the config file, the encoding variable (illumina, sanger, solexa) is used as the `PL` tag in the read groups. Picard is called several times in succession in the Picard SAM handler. Picard is very strict in its validation for BAM headers, and `PL=sanger` is an illegal tag/value combination. It could be that this causes an error, and an empty BAM file is written to disk on the first call to Picard. Successive calls to Picard would then try to read an empty BAM file, and throw a truncated file error.

Try setting `VALIDATION_STRINGENCY=silent` in Picard to see if this fixes the truncated file error. If it does, then you'll have to re-work how the encoding/platform variables are treated. Quality score encoding is not the same as sequencing platform, anyway.

**Comment by Aerin13** [comment]
Commit [9921ebc](https://github.com/MorrellLAB/sequence_handling/commit/9921ebcdc6b21f7e2cb3c79223a356178532cb86) fixed this issue.
