### ISSUE TITLE
Add Samtools version to Config file

### ISSUE THREAD

**Issue by fervet01** [MorrellLAB/sequence_handling#31]
Please add Samtools version with full path to Config file. Current version only states "module load samtools" which loads the default version. 

Desired version pls path:

/panfs/roc/groups/9/morrellp/public/Modules/samtools_ML/1.3.1

**Comment by Aerin13** [comment]
This issue has been addressed in the latest commit. Please pull the latest version and make sure to change your personal Config file. Thank you for bringing this to our attention!
