### ISSUE TITLE
Quality Assessment not using alternate samples specified

### ISSUE THREAD

**Issue by ChaochihL** [MorrellLAB/sequence_handling#32]
## Type of issue

- [x] Bug
- [ ] Feature request

---

### Have you looked at the wiki?

The wiki is located [here](https://github.com/MorrellLAB/sequence_handling/wiki)

- [x] Yes
- [ ] No

### Which handler are you having trouble with?

Quality Assessment

### Describe your problem

When I provide an alternate sample list (i.e. sample list for trimmed fastq files) for the ALTERNATE_SAMPLES variable, sequence handling calls on the RAW_SAMPLES variable. 

### What is the error message being generated?

There is no error message, Quality Assessment runs and finishes without errors, but runs Quality Assessment on the RAW_SAMPLES instead of the ALTERNATE_SAMPLES.

```shell
# Put your error message here

```

### Copy the part of the config file used by this handler

```shell
#   Shared values go here

```

```shell
#   Handler-specific values go here
#   Config file Line 9
RAW_SAMPLES=
#   Config file Line 77
ALTERNATE_SAMPLES=
```

```shell
#   In sequence_handling script
#   Line 58 only checks for sample list under RAW_SAMPLES not ALTERNATE_SAMPLES
checkSamples "${RAW_SAMPLES}" # Check to see if samples and sample list exists

#   Line 61 only sources Quality_Assessment for RAW_SAMPLES not ALTERNATE_SAMPLES
echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Quality_Assessment.sh && Quality_Assessment ${RAW_SAMPLES} ${OUT_DIR} ${PROJECT}" | qsub -l "${QA_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_Quality_Assessment
```

```shell
#   Dependency definitions go here

```

### Has anyone else been able to replicate your error?

- [ ] Yes
- [ ] No

---

### What new thing is being added?

- [ ] New handler
- [ ] Modification to handler

### Do you have a script for this change? Please note that we can implement your code faster if you write everything as [BASH functions](http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-8.html).

- [ ] Yes
- [ ] No

If yes, please make sure the code is posted online and link to it below:

[name of code exerpt](link.to.code.exerpt)

Good hosting sites are [GitHub](https://github.com) and [GitHub Gist](https://gist.github.com).

**Comment by Aerin13** [comment]
The latest commit should fix this issue, but I haven't done extensive testing. Could you please pull the latest version and re-try Quality_Assessment? Please let me know if there are still bugs.

**Comment by ChaochihL** [comment]
Thanks! I've only tested it on one set of samples, but it worked.
