### ISSUE TITLE
Add check for reference.dict file required for HaplotypeCaller

### ISSUE THREAD

**Issue by ChaochihL** [MorrellLAB/sequence_handling#34]
If you're filling this out for a bug in the code, please include the following information:
    - The handler that's giving you an issue

HaplotypeCaller

    - The error message

```bash
##### ERROR MESSAGE: Fasta dict file /panfs/roc/groups/9/morrellp/vonde026/Workshop/Yeast/S288C_reference_genome_R64-2-1_20150113/S288C_reference_sequence_R64-2-1_20150113.dict for reference /panfs/roc/groups/9/morrellp/vonde026/Workshop/Yeast/S288C_reference_genome_R64-2-1_20150113/S288C_reference_sequence_R64-2-1_20150113.fasta does not exist. Please see https://software.broadinstitute.org/gatk/documentation/article?id=1601 for help creating it.
```
    - A copy of the section in your Config for the relevant handler

```bash
#   What are our Qsub settings for Haplotype_Caller?
#       Below are the recommended settings
HC_QSUB="mem=250gb,nodes=1:ppn=24,walltime=24:00:00"

#   Which queue are we submitting the job to?
HC_QUEUE="ram256g"

#   Where is the list of finished BAM files?
#       To generate this list, use sample_list_generator.sh
#       located at /sequence_handling/HelperScripts/sample_list_generator.sh
FINISHED_BAM_LIST=/panfs/roc/groups/9/morrellp/vonde026/Workshop/Yeast/SAM_Processing/SAMtools/Yeast_Sample_BAM.txt

#   What is the nucleotide diversity per base pair (Watterson's theta)?
#       For barley: 0.008
#       For soybean: 0.001
THETA=0.005
```
    - A copy of the dependencies section in your Config

    - Here is a link to code that will create the reference.dict file. I have run the script and it works.

Code link: [fasta_seq_dict.job](https://github.com/MorrellLAB/Yeast/blob/master/sequence_processing/scripts/fasta_seq_dict.job)

**Comment by Aerin13** [comment]
This issue was fixed in the [latest commit](https://github.com/MorrellLAB/sequence_handling/commit/d8b1b33e85eee4b290f61593a625cedb3513e61a). All GATK handlers should now check for a reference.dict and generate one if it does not exist. Thank you for pointing this out.
