### ISSUE TITLE
sequence handling workflow numbers

### ISSUE THREAD

**Issue by pmorrell** [MorrellLAB/sequence_handling#42]
The usage message for the primary sequence_handling script does not list the handlers by the correct number for each option. For example, NP_Quality_Assessment is listed as "17" but it is option 15 in script, so option 17 starts read mapping. Other handlers at the bottom of the list are also off by 2 values.

Usage:  sequence_handling <handler> <config>
Where:  <handler> is one of:
            Recommended workflow:
                1 | Quality_Assessment
                2 | Adapter_Trimming
                3 | Read_Mapping
                4 | SAM_Processing
                5 | Coverage_Mapping
                6 | Haplotype_Caller
                7 | Genomics_DB_Import
                8 | Genotype_GVCFs
                9 | Create_HC_Subset
                10 | Variant_Recalibrator
                11 | Variant_Filtering
                12 | Variant_Analysis
            Other handlers:
                13 | GBS_Demultiplex (in progress)
                14 | Quality_Trimming
                15 | Realigner_Target_Creator
                16 | Indel_Realigner
            Nanopore workflow:
                17 | NP_Quality_Assessment (in progress)
                18 | NP_Adapter_Trimming (in progress)
                19 | NP_Read_Mapping (in progress)
                20 | NP_SAM_Processing (in progress)

**Comment by ChaochihL** [comment]
Hi @pmorrell, the commit 1ec3c27f57add6b23dfaf730a39ed217bf01ba72 fixes this issue. Thanks for reporting!
