### ISSUE TITLE
A bug in Line 173 of 4_Quality_Trimming.sh

### ISSUE THREAD

**Issue by lilei1** [MorrellLAB/sequence_handling#8]
in Line 173 of 4_Quality_Trimming.sh
Rscript "${helper}"/plot_seqqs.R "${stats}" "${sample_name}" should be 
Rscript "${helper}"/plot_seqqs.R "${stats}"  "${sampleName}"
I have already revised this place.

**Comment by mojaveazure** [comment]
This issue is irrelevant in the current version of `sequence_handling`, will close in two days
