### ISSUE TITLE
a bug in "Helper_Scripts/plot_seqqs.R"

### ISSUE THREAD

**Issue by lilei1** [MorrellLAB/sequence_handling#9]
I will always have this Error: "Error in read.table(Trimmed.forward.nucl.name, header = TRUE) : 
 no lines available in input
Execution halted"
I figured out how to solve this problem:
for this script "Helper_Scripts/plot_seqqs.R", when use "read.table", I would like to use "try(read.table)" because this won't stop the whole program even the file is empty. Then when call the plot function, e.g. "BaseCompositionPlot", need to use "if else" statement to judge if the file is empty or not.

**Comment by mojaveazure** [comment]
This error is irrelevant with the current version of `sequence_handling`, will close in two days
